# Simple Impalib GitHub Action (CI Pipeline)
# Version: 0.2.0

name: Impalib CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build:
    name: Build Job
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
    - name: Build Python (CPP) Wrapper
      run: |
            python3 -m pip install --user . -v
            echo "Project built successfully."
  
  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
    - name: Lint Python Code
      run: |
            pip install ruff
            ruff check
            echo "Linting completed successfully."

  test:
    name: Unit Test Job
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Run Unit Tests
      run: |
            python -m pip install --user . -v
            cmake -B build && cmake --build build && cd build/test/src
            ./unit_test_kc_mwm.sh
            ./unit_test_tsp.sh
            ./unit_test_ksat.sh
            echo "Unit tests completed successfully."
