# Simple Impalib GitHub Action (CI Pipeline)
# Version: 0.3.0

name: Impalib CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build:
    name: Build Job
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
    - name: Build Python (CPP) Wrapper
      run: |
            python3 -m pip install --user . -v
            echo "Project built successfully."
  
  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
    - name: Lint Python Code
      run: |
            pip install ruff
            ruff check
  
  demo:
    name: Demo Job
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Run CPP Demos
      run: |
            python3 -m pip install --user . -v
            cd examples/KcMwm && cmake -B build && cmake --build build && cd build && ./demo
            cd .. && cd Tsp && cmake -B build && cmake --build build && cd build && ./demo
            cd .. && cd Ksat && cmake -B build && cmake --build build && cd build && ./demo
            echo "CPP Demos executed successfully."
    - name: Run Python Demos
      run: |
           python3 -m pip install --user . -v
           cd test/python_kc_mwm/src
           python3 main_pure_optimized.py --nITER=400 --filteringFlag=True --alpha=0.9 --PPFlag=True --threshold=-0.0001
           cd ../.. && cd test/python_tsp/src
           python3 main_tsp.py --nNodes=10 --filteringFlag=True --alpha=0.5 --augmFlag=True --threshold=-0.0001 --nITER=200 --randomTestFlag=True
           cd ../.. && cd test/python_ksat/src
           python3 main_ksat.py --filteringFlag=True --threshold=-0.0001 --nITER=200 --alpha=0.5 --randomTestFlag=True --nConstraints=20 --nVariables=10 --kVariable=3
            echo "Python Demos executed successfully."