# Simple Impalib Build Stage GitHub Workflow
# Version: 0.1.0

name: Impalib Build

on: push

jobs:
  build:
    name: Impalib Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Build Python Wrapper
        uses: actions/checkout@v4
      - run: |
            python3 -m pip install . -v
            echo "Project built successfully."